# yaml-language-server: $schema=./values.schema.json

global:
  domain: c-3f6e6b4.kyma.ondemand.com
  imagePullSecret:
    name: docker-registry
  image:
    registry: docker.io/sriniv7654
    tag: latest
srv:
  bindings:
    auth:
      serviceInstanceName: xsuaa
    db:
      serviceInstanceName: hana
    destination:
      serviceInstanceName: destination
  image:
    repository: single-srv
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /health
    readiness:
      path: /health
  networkSecurity:
    allowNamespaceInternal: true  
approuter:
  bindings:
    auth:
      serviceInstanceName: xsuaa
    html5-apps-repo-runtime:
      serviceInstanceName: html5-apps-repo-runtime
  image:
    repository: single-approuter
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /
    readiness:
      path: /
  env:
    EXTERNAL_REVERSE_PROXY: "true"
  envFrom:
    - configMapRef:
        name: "{{ .Release.Name }}-approuter-configmap"
xsuaa:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    tenant-mode: dedicated
    xsappname: singleui-{{ .Release.Namespace }}
    scopes:
      - name: $XSAPPNAME.kymacapnodejsviewer
        description: Access Books data
    authorities:
      - $ACCEPT_GRANTED_AUTHORITIES
      - $XSAPPNAME.kymacapnodejsviewer
    role-templates:
      - name: KymaCapNodeJsDemoRoleTemplate
        description: Role Template for accessing Books
        scope-references:
          - $XSAPPNAME.kymacapnodejsviewer
    role-collections:
      - name: CAPNodeJsUserRC
        description: Role Collection for Kyma CAP Node.js App
        role-template-references:
          - $XSAPPNAME.KymaCapNodeJsDemoRoleTemplate
    oauth2-configuration:
      redirect-uris:
        - https://singleui-approuter-sri.c-3f6e6b4.kyma.ondemand.com/**
        - https://singleui-approuter-sri.c-3f6e6b4.kyma.ondemand.com/login/callback
hana-deployer:
  image:
    repository: single-hana-deployer
  bindings:
    hana:
      serviceInstanceName: hana
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
hana:
  serviceOfferingName: hana
  servicePlanName: hdi-shared
backendDestinations:
  srv-api:
    service: srv
destination:
  serviceOfferingName: destination
  servicePlanName: lite
  parameters:
    version: 1.0.0
    HTML5Runtime_enabled: true
html5-apps-repo-host:
  serviceOfferingName: html5-apps-repo
  servicePlanName: app-host
html5-apps-deployer:
  env:
    SAP_CLOUD_SERVICE: single.service
  image:
    repository: single-html5-deployer
  bindings:
    xsuaa:
      serviceInstanceName: xsuaa
    destination:
      serviceInstanceName: destination
    html5-apps-repo:
      serviceInstanceName: html5-apps-repo-host
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
  envFrom:
    - configMapRef:
        name: "{{ .Release.Name }}-html5-apps-deployer-configmap"
html5-apps-repo-runtime:
  serviceOfferingName: html5-apps-repo
  servicePlanName: app-runtime
