//@ui5-bundle project1/Component-preload.js
sap.ui.predefine("project1/Component", ["sap/ui/core/UIComponent","project1/model/models"],(e,t)=>{"use strict";return e.extend("project1.Component",{metadata:{manifest:"json",interfaces:["sap.ui.core.IAsyncContentCreation"]},init(){e.prototype.init.apply(this,arguments);this.setModel(t.createDeviceModel(),"device");this.getRouter().initialize()}})});
sap.ui.predefine("project1/controller/App.controller", ["sap/ui/core/mvc/Controller"],e=>{"use strict";return e.extend("project1.controller.App",{onInit(){}})});
sap.ui.predefine("project1/controller/View1.controller", ["sap/ui/core/mvc/Controller","sap/ui/model/json/JSONModel","sap/m/ColumnListItem","sap/m/Text"],(e,t,n,o)=>{"use strict";return e.extend("project1.controller.View1",{onInit(){const e=new t;this.getView().setModel(e,"user");const n=this.getOwnerComponent().getModel();const o=n.bindContext("/userInfo()");o.requestObject().then(t=>{e.setProperty("/email",t.name)});const s=this.getOwnerComponent().getRouter();s.getRoute("RouteView1").attachPatternMatched(this.onRoutePatternMatched,this)},onRoutePatternMatched:function(){const e=this.byId("booksTable");const t=this.byId("authMessage");const s=this.getOwnerComponent().getModel();const i=s.bindContext("/isAuthorized()");i.requestObject().then(()=>{e.bindItems({path:"/Books",template:new n({cells:[new o({text:"{ID}"}),new o({text:"{title}"}),new o({text:"{stock}"})]})})}).catch(n=>{if(n&&/403|forbidden/i.test(n.message)){e.setVisible(false);t.setVisible(true)}})}})});
sap.ui.predefine("project1/model/models", ["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
sap.ui.require.preload({
	"project1/i18n/i18n.properties":'# This is the resource bundle for project1\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=App Title\n\n#YDES: Application description\nappDescription=An SAP Fiori application.\n#XTIT: Main view title\ntitle=App Title',
	"project1/manifest.json":'{"_version":"1.65.0","sap.app":{"id":"project1","type":"application","i18n":{"bundleUrl":"i18n/i18n.properties","supportedLocales":[""]},"applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","sourceTemplate":{"id":"@sap/generator-fiori:basic","version":"1.18.4","toolsId":"0ff86758-e283-4c75-83b4-0e7dcefdbc44"},"dataSources":{"mainService":{"uri":"/odata/v4/catalog/","type":"OData","settings":{"annotations":[],"odataVersion":"4.0"}}}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":true,"dependencies":{"minUI5Version":"1.139.0","libs":{"sap.m":{},"sap.ui.core":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"project1.i18n.i18n","supportedLocales":[""]}},"":{"dataSource":"mainService","preload":true,"settings":{"operationMode":"Server","autoExpandSelect":true,"earlyRequests":true}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","controlAggregation":"pages","controlId":"app","transition":"slide","type":"View","viewType":"XML","path":"project1.view","async":true,"viewPath":"project1.view"},"routes":[{"name":"RouteView1","pattern":":?query:","target":["TargetView1"]}],"targets":{"TargetView1":{"id":"View1","name":"View1"}}},"rootView":{"viewName":"project1.view.App","type":"XML","id":"App","async":true}}}',
	"project1/view/App.view.xml":'<mvc:View controllerName="project1.controller.App"\n    displayBlock="true"\n    xmlns:mvc="sap.ui.core.mvc"\n    xmlns="sap.m"><App id="app"></App></mvc:View>',
	"project1/view/View1.view.xml":'<mvc:View controllerName="project1.controller.View1"\n    xmlns:mvc="sap.ui.core.mvc"\n    xmlns="sap.m"><Page id="page" title="{i18n>title}"><headerContent><Title text="Hello, {user>/email}" level="H2" class="sapUiSmallMarginBegin" /></headerContent><content><MessageStrip id="authMessage" text="You are not authorized to view this data. Please check your roles." type="Error" showIcon="true" class="sapUiSmallMarginBottom" visible="false" /><Table id="booksTable"\n                width="50%"><columns><Column><Text text="ID" /></Column><Column><Text text="Title" /></Column><Column><Text text="Stock" /></Column></columns><items><ColumnListItem><cells><Text text="{ID}" /><Text text="{title}" /><Text text="{stock}" /></cells></ColumnListItem></items></Table></content></Page></mvc:View>\n'
});
//# sourceMappingURL=Component-preload.js.map
